################################################################################
# Author setup
## [author]
################################################################################
# there is no link ;) this is a weird configuration
################################################################################
name = "Jane Doe"
homepage = "https://example.com/jane-doe/"
content = "sitewide/authorfooter/index.md"

[photo]
name = "jane-doe.jpg"
title = "Jane Doe the totally famous author"

[format]
layout = "card"
