################################################################################
# Author setup
## [author]
################################################################################
# there is no link ;) this is a weird configuration
################################################################################
name = "Aesop"
homepage = "https://en.wikipedia.org/wiki/Aesop"
content = "sitewide/authorfooter/index.md"

[photo]
name = "aesop.jpg"
title = "Aesop the Greek"

[format]
layout = "card"
