defaultMarkdownHandler = "goldmark"

[goldmark]

  [goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true

  [goldmark.parser]
    attribute = true
    autoHeadingID = true
    autoHeadingIDType = "github"

  [goldmark.renderer]
    hardWraps = false
    unsafe = true
    xhtml = false
