################################################################################
# Markup configuration
## [markup]
################################################################################
# see
# ...
################################################################################
[goldmark.renderer]
unsafe = false
