################################################################################
# Markup configuration
## [markup]
################################################################################
# see
# https://gohugo.io/getting-started/configuration-markup
################################################################################
[goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true

[goldmark.parser]
attribute = true
autoHeadingID = true
autoHeadingIDType = "github"

[goldmark.renderer]
hardWraps = false
unsafe = false
xhtml = false

[highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ""
lineAnchors = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "monokai"
tabWidth = 4

[tableOfContents]
endLevel = 3
ordered = false
startLevel = 2
