################################################################################
# Media type setup
## [mediaTypes]
################################################################################
# see
# https://gohugo.io/templates/output-formats
################################################################################
["text/netlify"]
suffixes = [""]
delimiter = ""
