################################################################################
# Media type setup
## [mediaTypes]
################################################################################
# see
# ...
################################################################################
["text/netlify"]
suffixes = [""]
delimiter = ""
