################################################################################
# Menu setup
## [menu]
################################################################################
# see
# https://gohugo.io/content-management/menus/#add-non-content-entries-to-a-menu
################################################################################
[[main]]
name = "DNB"
weight = 250
identifier = "dnb"
url = "https://davids-neighbour.com"
pre = "icons/user-tie.svg"
