################################################################################
# Output formats and structure
## [outputFormats]
################################################################################
# see
# http://gohugo.io/templates/output-formats/
# https://gohugo.io/news/http2-server-push-in-hugo/
################################################################################
[Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[REDIR]
mediatype = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true

[HEADERS]
mediatype = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true
