################################################################################
# Output structure
## [outputs]
################################################################################
# see
# https://gohugo.io/templates/output-formats#readout
################################################################################
home = [ "HTML", "RSS", "Algolia", "REDIR", "HEADERS" ]
page = [ "HTML" ]
post = [ "HTML" ]
