################################################################################
# Output structure
## [outputs]
################################################################################
# see
# ...
################################################################################
home = [ "HTML", "RSS", "Algolia", "REDIR", "HEADERS" ]
page = [ "HTML" ]
post = [ "HTML" ]
