#############################################################
# Social Media Setup
#############################################################
[facebook]
profileid = "517050641"    # patrick.kollitsch
pageid = "6967849771"      # samuisamui
appid = "2047624572136513" # samui-samui.de
profileslug = "patrick.kollitsch"

[twitter]
profileid = "davidsneighbour"
siteid = "samui2"
theme ="dark"
linkcolor = "#d02d19"
dnt = "on"
csp = "on"

[snapchat]
profileid = "pkollitsch"

[whatsapp]
profileid = "66878979350"
