################################################################################
# Permalink setup
## [permalinks]
################################################################################
# see
# https://gohugo.io/content-management/urls/
################################################################################
posts = "/:year/:month/:slug/"
tags = "/:section/:slug/"
