################################################################################
# Sitemap setup
## [sitemap]
################################################################################
# see
# ...
################################################################################
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.8
