################################################################################
# Taxonomy setup
## [taxonomies]
################################################################################
# see
# ...
################################################################################
tag = "tags"
feiertag = "feiertage"
