################################################################################
# Taxonomy setup
## [taxonomies]
################################################################################
# see
# https://gohugo.io/content-management/taxonomies/#configuring-taxonomies
################################################################################
tag = "tags"
category = "categories"
